### ISSUE TITLE
DMCA violation

### ISSUE THREAD

**Issue by Lucent** [YorgeR17/ptable#1]
This repo contains copyrighted code from ptable.com and needs to be removed.

**Comment by YorgeR17** [comment]
That's crazy your freaking out about a 7 year old periodic table lol, As you can see on the history it has 0 edits, hasn't been looked at even in 7 years. We where shown how to build this as a high school project. Regardless its removed.

**Comment by Lucent** [comment]
The repo itself still contains the code and remains in violation of the trademark "ptable" as applied to electronic periodic tables (USPTO registration 87536072).

I will get in touch with GitHub themselves to have the repo itself removed since you seem emotionally volatile and aggressively uncooperative.
